#!/usr/bin/env bash

# Consolidate all evaluation metrics into unified CSVs.
#
# This script scans the ``results/summary`` directory for metrics
# generated by previous evaluation scripts (method metrics, MIA
# metrics, LiRA metrics, backdoor metrics, and attack metrics) and
# produces a single CSV ``all_metrics.csv`` containing all rows with
# an additional column indicating the source file.  It also ensures
# that ``attack_metrics.csv`` and other intermediate CSVs are present
# in the summary directory.  Usage:
#   bash scripts/50_summary.sh [results_dir]
#

set -e

OUTDIR="${1:-.}"
SUMMARY_DIR="$OUTDIR/results/summary"
mkdir -p "$SUMMARY_DIR"

ALL_CSV="$SUMMARY_DIR/all_metrics.csv"
echo "file,tag,mu,..." > "$ALL_CSV"

# Helper to append metrics with file label
append_csv() {
  local src_file="$1"
  local label="$2"
  if [[ -f "$src_file" ]]; then
    tail -n +2 "$src_file" | while IFS= read -r line; do
      echo "$label,$line" >> "$ALL_CSV"
    done
  fi
}

# Append each metrics file
append_csv "$SUMMARY_DIR/attack_metrics.csv" "attack"
append_csv "$SUMMARY_DIR/method_metrics.csv" "method"
append_csv "$SUMMARY_DIR/mia_metrics.csv" "mia"
append_csv "$SUMMARY_DIR/lira_metrics.csv" "lira"
append_csv "$SUMMARY_DIR/backdoor_metrics.csv" "backdoor"

echo "Summary CSV generated at $ALL_CSV"
